config/routes.rb
Rails.application.routes.draw do
  namespace :potepan do
    get 'taxons/show'
  end

  # This line mounts Spree's routes at the root of your application.
  # This means, any requests to URLs such as /products, will go to Spree::ProductsController.
  # If you would like to change where this engine is mounted, simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here, as Spree relies on it being the default of "spree"
  mount Spree::Core::Engine, at: '/'

  namespace :potepan do
    root to: 'home#index'
    resources :products, param: :slug_or_id, only: [:index, :show] do
      get :search, on: :collection
    end
    get '/categories/:taxon_id', to: 'taxons#show', as: :taxon

    post '/add_cart', to: 'orders#add_cart'
    get '/cart', to: 'orders#edit'
    patch '/cart', to: 'orders#update'

    # get '/',                        to: 'sample#index'
    get 'index',                    to: 'sample#index'
    get :product_grid_left_sidebar, to: 'sample#product_grid_left_sidebar'
    get :product_list_left_sidebar, to: 'sample#product_list_left_sidebar'
    get :single_product,            to: 'sample#single_product'
    get :cart_page,                 to: 'sample#cart_page'
    get :checkout_step_1,           to: 'sample#checkout_step_1'
    get :checkout_step_2,           to: 'sample#checkout_step_2'
    get :checkout_step_3,           to: 'sample#checkout_step_3'
    get :checkout_complete,         to: 'sample#checkout_complete'
    get :blog_left_sidebar,         to: 'sample#blog_left_sidebar'
    get :blog_right_sidebar,        to: 'sample#blog_right_sidebar'
    get :blog_single_left_sidebar,  to: 'sample#blog_single_left_sidebar'
    get :blog_single_right_sidebar, to: 'sample#blog_single_right_sidebar'
    get :about_us,                  to: 'sample#about_us'
    get :tokushoho,                 to: 'sample#tokushoho'
    get :privacy_policy,            to: 'sample#privacy_policy'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/headers/topbar/_current_cart.html.erb
<a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-shopping-cart"></i>
  <%= current_order.try(:display_total) || '$0' %>
</a>
<ul class="dropdown-menu dropdown-menu-right">
  <% if current_order.nil? || current_order.line_items.empty? %>
    <li>カートに商品はありません</li>
  <% else %>
    <li>カートに商品が <%= current_order.line_items.count %> 点あります</li>
    <%= render partial: 'layouts/headers/topbar/line_item', collection: current_order.line_items %>
    <li>
      <div class="btn-group" role="group" aria-label="...">
        <%= button_tag type: 'button', onclick: "window.location.href='#{potepan_cart_path}'", class: 'btn btn-default' do %>
          カートを見る
        <% end %>
        <button type="button" class="btn btn-default">購入する</button>
      </div>
    </li>
  <% end %>
</ul>

app/views/layouts/headers/topbar/_line_item.html.erb
<li>
  <%= link_to potepan_product_path(line_item.variant.product.slug) do %>
    <div class="media">
      <% if line_item.variant.images.length == 0 %>
        <%= image_tag(line_item.variant.product.display_image.attachment(:small), :class => "media-left media-object", width: '64px') %>
      <% else %>
        <%= image_tag(line_item.variant.images.first.attachment.url(:small), :class => "media-left media-object", width: '64px') %>
      <% end %>
      <div class="media-body">
        <h5 class="media-heading"><%= line_item.name %><br>
          <span><%= line_item.single_money.to_html %> X <%= line_item.quantity %></span>
        </h5>
      </div>
    </div>
  <% end %>
</li>

app/views/layouts/headers/topbar/_login_or_signup.html.erb
<span><a data-toggle="modal" href='#login'>Log in</a><small>or</small><a data-toggle="modal" href='#signup'>Create an account</a></span>

app/views/layouts/headers/topbar/_searchbox_form.html.erb
<a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-search"></i></a>
<ul class="dropdown-menu dropdown-menu-right">
  <li>
    <%= form_tag search_potepan_products_path, enforce_utf8: false, method: :get do %>
    <span class="input-group">
      <span class="input-group-addon">Search</span>
      <%= text_field_tag('keyword', nil, placeholder:'Search...', class: 'form-control', 'aria-describedby' => 'basic-addon2') %>
    </span>
    <% end %>
  </li>
</ul>

app/views/layouts/headers/topbar/_social_link.html.erb
<li><a href="<%= social[:url] %>"><i class="fa fa-<%= social[:name] %>"></i></a></li>