config/routes.rb
Rails.application.routes.draw do
  namespace :potepan do
    get 'taxons/show'
  end

  # This line mounts Spree's routes at the root of your application.
  # This means, any requests to URLs such as /products, will go to Spree::ProductsController.
  # If you would like to change where this engine is mounted, simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here, as Spree relies on it being the default of "spree"
  mount Spree::Core::Engine, at: '/'

  namespace :potepan do
    root to: 'home#index'
    resources :products, param: :slug_or_id, only: [:index, :show] do
      get :search, on: :collection
    end
    get '/categories/:taxon_id', to: 'taxons#show', as: :taxon

    post '/add_cart', to: 'orders#add_cart'
    get '/cart', to: 'orders#edit'
    patch '/cart', to: 'orders#update'

    # get '/',                        to: 'sample#index'
    get 'index',                    to: 'sample#index'
    get :product_grid_left_sidebar, to: 'sample#product_grid_left_sidebar'
    get :product_list_left_sidebar, to: 'sample#product_list_left_sidebar'
    get :single_product,            to: 'sample#single_product'
    get :cart_page,                 to: 'sample#cart_page'
    get :checkout_step_1,           to: 'sample#checkout_step_1'
    get :checkout_step_2,           to: 'sample#checkout_step_2'
    get :checkout_step_3,           to: 'sample#checkout_step_3'
    get :checkout_complete,         to: 'sample#checkout_complete'
    get :blog_left_sidebar,         to: 'sample#blog_left_sidebar'
    get :blog_right_sidebar,        to: 'sample#blog_right_sidebar'
    get :blog_single_left_sidebar,  to: 'sample#blog_single_left_sidebar'
    get :blog_single_right_sidebar, to: 'sample#blog_single_right_sidebar'
    get :about_us,                  to: 'sample#about_us'
    get :tokushoho,                 to: 'sample#tokushoho'
    get :privacy_policy,            to: 'sample#privacy_policy'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_filter_area.html.erb
<div class="row filterArea">

  <div class="col-xs-6">
    <%= form_tag request.path, enforce_utf8: false, method: :get do %>
      <%= hidden_field_tag 'tshirt-size', params['tshirt-size'] if params['tshirt-size'] %>
      <%= hidden_field_tag 'tshirt-color', params['tshirt-color'] if params['tshirt-color'] %>
      <%= hidden_field_tag 'keyword', params['keyword'] if params['keyword'] %>
      <%= hidden_field_tag 'view', params['view'] if params['view'] %>
      <%= select_tag(:sort, options_for_select(@product_filter.sort_select_collection, {selected: params[:sort] || 'newest'}), class: 'select-drop', onchange: 'this.form.submit();') %>
    <% end %>
  </div>
  <div class="col-xs-6">
    <div class="btn-group pull-right" role="group">
      <%= content_tag :button, class: "btn btn-default #{@product_filter.list_view? ? '' : 'active'}",
            onclick: "window.location.href='#{url_for(params.permit(*ProductFilter::VALID_PARAMETER).merge(view: 'grid'))}'" do %>
        <i class="fa fa-th" aria-hidden="true"></i><span>Grid</span>
      <% end %>
      <%= content_tag :button, class: "btn btn-default #{@product_filter.list_view? ? 'active' : ''}",
            onclick: "window.location.href='#{url_for(params.permit(*ProductFilter::VALID_PARAMETER).merge(view: 'list')) }'" do %>
        <i class="fa fa-th-list" aria-hidden="true"></i><span>List</span>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_grid_item.html.erb
<div class="col-sm-<%= 12 / column %> col-xs-12">
  <div class="productBox">
    <div class="productImage clearfix">
      <%= image_tag product.display_image.attachment.url  %>
      <div class="productMasking">
        <ul class="list-inline btn-group" role="group">
          <li><a data-toggle="modal" href=".login-modal" class="btn btn-default"><i class="fa fa-heart"></i></a></li>
          <li>
            <%= link_to potepan_cart_path, class: 'btn btn-default' do %>
              <i class="fa fa-shopping-cart"></i>
            <% end %>
          </li>
          <li><a data-target="#modal-<%= product.id %>" class="btn btn-default" data-toggle="modal" href=".quick-view" ><i class="fa fa-eye"></i></a></li>
        </ul>
      </div>
    </div>
    <div class="productCaption clearfix">
      <%= link_to potepan_product_path(product.slug) do %>
        <h5><%= product.name %></h5>
      <% end %>
      <h3><%= product.price %></h3>
    </div>
  </div>
</div>

<%= render partial: 'shared/modal/product_quick_view', locals: { product: product } %>

app/views/shared/_list_item.html.erb
<div class="col-xs-12">
  <div class="media">
    <div class="media-left">
      <%= image_tag list_item.display_image.attachment.url  %>
      <span class="maskingImage"><a data-target="#modal-<%= list_item.id %>" data-toggle="modal" href=".quick-view" class="btn viewBtn">Quick View</a></span>
    </div>
    <div class="media-body">
      <h4 class="media-heading">
        <%= link_to list_item.name , potepan_product_path(list_item.slug) %>
      </h4>
      <p><%= list_item.description %></p>
      <h3><%= list_item.price %></h3>
      <div class="btn-group" role="group">
        <button type="button" class="btn btn-default" data-toggle="modal" data-target=".login-modal"><i class="fa fa-heart" aria-hidden="true"></i></button>
        <%= content_tag :button, class: "btn btn-default", onclick: "window.location.href='#{potepan_cart_path}'" do %>
          <i class="fa fa-shopping-cart" aria-hidden="true"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

<%= render partial: 'shared/modal/product_quick_view', locals: { product: list_item } %>

app/views/shared/_page_header.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-6">
      <div class="page-title">
        <h2><%= page[:name] || page.name %>
          <% if page[:filter_name] %>
            <span style="margin-left: 8px;">: <%= page[:filter_name] %></span>
          <% elsif page[:keyword] %>
            <span style="margin-left: 8px;">: <%= params[:keyword] %></span>
          <% end %>
        </h2>
      </div>
    </div>
    <div class="col-xs-6">
      <ol class="breadcrumb pull-right">
        <li>
          <%= link_to 'Home', potepan_root_path %>
        </li>
        <li>
          <a href="#">shop</a>
        </li>
        <li class="active"><%= page[:name] || page.name %></li>
      </ol>
    </div>
  </div>
</div>

app/views/shared/_page_header_table_block.html.erb
<div class="container">
  <div class="tableBlock">
    <div class="row tableInner">
      <div class="col-xs-12">
        <div class="page-title">
          <h2><%= name %></h2>
          <ol class="breadcrumb">
            <li>
              <%= link_to 'Home', potepan_root_path %>
            </li>
            <li class="active"><%= name %></li>
          </ol>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_partners.html.erb
<section class="lightSection clearfix">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <div class="owl-carousel partnersLogoSlider">
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-01.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-02.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-03.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-04.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-05.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-01.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-02.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-03.png", :alt => "partner-img") %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/shared/_sidebar.html.erb
<div class="col-md-3 col-sm-4 col-xs-12 sideBar">

  <div class="panel panel-default">
    <div class="panel-heading">商品カテゴリー</div>
    <div class="panel-body">
      <div class="collapse navbar-collapse navbar-ex1-collapse navbar-side-collapse">
        <% @roots.each do |root| %>
        <ul class="nav navbar-nav side-nav">
          <li>
            <a href="javascript:;" data-toggle="collapse" data-target="#category-<%= root.id %>"><%= root.name %><i class="fa fa-plus"></i></a>
            <ul id="category-<%= root.id %>" class="collapse collapseItem">
              <li>
                <%= link_to potepan_taxon_path(root.id) do  %>
                  <i class="fa fa-caret-right" aria-hidden="true"></i>ALL <%= root.name %>

                <% end %>
              </li>
              <% root.leaves.each do |child| %>
              <li>
                <%= link_to potepan_taxon_path(child.id) do %>
                  <i class="fa fa-caret-right" aria-hidden="true"></i><%= child.name %> <span>(<%= child.products.count %>)</span>
                <% end %>
              </li>
              <% end %>
            </ul>
          </li>
        </ul>
        <% end %>
      </div>
    </div>
  </div>

  <% if false %>
  <div class="panel panel-default priceRange">
    <div class="panel-heading">値段から探す</div>
    <div class="panel-body clearfix">
      <div class="price-slider-inner">
        <span class="amount-wrapper">
          <input type="text" id="price-amount-1" readonly>
          <strong>-</strong>
          <input type="text" id="price-amount-2" readonly>
        </span>
        <div id="price-range"></div>
      </div>
      <input class="btn btn-default" type="submit" value="絞り込む">
      <!-- <span class="priceLabel">Price: <strong>12 円- 30<円/strong></span> -->
    </div>
  </div>
  <% end %>
  <div class="panel panel-default filterNormal">
    <div class="panel-heading">Tシャツの色から探す</div>
    <div class="panel-body">
      <%= option_type_filter_menu_by(name: 'tshirt-color') %>
    </div>
  </div>

  <div class="panel panel-default filterNormal">
    <div class="panel-heading">Tシャツのサイズから探す</div>
    <div class="panel-body">
      <%= option_type_filter_menu_by(name: 'tshirt-size') %>
    </div>
  </div>

</div>