config/routes.rb
Rails.application.routes.draw do
  namespace :potepan do
    get 'taxons/show'
  end

  # This line mounts Spree's routes at the root of your application.
  # This means, any requests to URLs such as /products, will go to Spree::ProductsController.
  # If you would like to change where this engine is mounted, simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here, as Spree relies on it being the default of "spree"
  mount Spree::Core::Engine, at: '/'

  namespace :potepan do
    root to: 'home#index'
    resources :products, param: :slug_or_id, only: [:index, :show] do
      get :search, on: :collection
    end
    get '/categories/:taxon_id', to: 'taxons#show', as: :taxon

    post '/add_cart', to: 'orders#add_cart'
    get '/cart', to: 'orders#edit'
    patch '/cart', to: 'orders#update'

    # get '/',                        to: 'sample#index'
    get 'index',                    to: 'sample#index'
    get :product_grid_left_sidebar, to: 'sample#product_grid_left_sidebar'
    get :product_list_left_sidebar, to: 'sample#product_list_left_sidebar'
    get :single_product,            to: 'sample#single_product'
    get :cart_page,                 to: 'sample#cart_page'
    get :checkout_step_1,           to: 'sample#checkout_step_1'
    get :checkout_step_2,           to: 'sample#checkout_step_2'
    get :checkout_step_3,           to: 'sample#checkout_step_3'
    get :checkout_complete,         to: 'sample#checkout_complete'
    get :blog_left_sidebar,         to: 'sample#blog_left_sidebar'
    get :blog_right_sidebar,        to: 'sample#blog_right_sidebar'
    get :blog_single_left_sidebar,  to: 'sample#blog_single_left_sidebar'
    get :blog_single_right_sidebar, to: 'sample#blog_single_right_sidebar'
    get :about_us,                  to: 'sample#about_us'
    get :tokushoho,                 to: 'sample#tokushoho'
    get :privacy_policy,            to: 'sample#privacy_policy'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/form/_cart_form.html.erb
<%= form_for :order, url: potepan_add_cart_path do |f| %>
  <% if product.variants.any? %>
    <span class="quick-drop">
      <%= variants_select_tag(product.variants) %>
    </span>
  <% else %>
    <%= hidden_field_tag 'variant_id', product.master.id %>
  <% end %>

  <span class="quick-drop">
    <%= quantity_select_tag(name: 'quantity') %>
  </span>
  <div class="btn-area">
    <%= content_tag :button, class: 'btn btn-primary btn-block', type: 'submit' do %>
      カートへ入れる<i class="fa fa-angle-right" area-hidden='true'></i>
    <% end %>
  </div>
<% end %>